name: Build SimpleTweaksPlugin with API4
on:
  push:
    branches:
      - api4
jobs:
  build:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: [windows-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Restore NuGet Packages
        run: nuget restore SimpleTweaksPlugin.sln

      - name: Download Dalamud staging
        run: |
            Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
            Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"
            
      - name: Build
        run: msbuild SimpleTweaksPlugin.sln /p:Configuration=Release

      - name: Extract Publish
        run: |
          Expand-Archive -Force ./bin/x64/Release.ILMerge/SimpleTweaksPlugin/latest.zip ./Artifact
          
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: api4-artifact
          path: ./Artifact/*